### ISSUE TITLE
Incompatible with Latest stable version (1.14.0)

### ISSUE THREAD

**Issue by m0urs** [NIIF/simplesamlphp-module-authtfaga#1]
Hi Frank,

could it be that this module is not compatibel with Latest stable version (1.14.0) of SimpleSAML? I changed two things in login.php and in general it seems to work. But the UI seems to be broken and I guess some more things are broken too. Have a look how the UI of the login page looks for me (enclosed screenshot).

Thanks,
Michael

![image](https://cloud.githubusercontent.com/assets/2588362/13227740/719e2c42-d998-11e5-9b94-c24bb674dbcc.png)

**Comment by sitya** [comment]
Hi,

> could it be that this module is not compatibel with Latest stable version (1.14.0) of SimpleSAML? I changed two things in login.php and in general it seems to work. But the UI seems to be broken and I guess some more things are broken too. Have a look how the UI of the login page looks for me (enclosed screenshot).

thanks for the report. There were two incompatibile line in www/login.php, I have fixed it. Now I checked with a 1.14.0 (commit: 03c6303) simplesamlphp and it worked fine.

**Comment by m0urs** [comment]
Hi Frank,

thanks a lot. However it still looks a bit strange to me. Please have a
look at this screenshot. This is what I get after I login with my user /
password and when the Google Authenticator code should run:

[image: Inline-Bild 1]

In general I would say it works, however soemthing still is broken. Maybe
something I did wrong?

Do you have any other idea?

Thanks,
Michael

2016-02-23 14:00 GMT+01:00 Frank Tamás notifications@github.com:

**Comment by sitya** [comment]
> On 2016. febr. 23., at 14:12, Michael Urspringer notifications@github.com wrote:
> 
> thanks a lot. However it still looks a bit strange to me. Please have a
> look at this screenshot.

I did.

> This is what I get after I login with my user /
> password and when the Google Authenticator code should run:
> 
> In general I would say it works, however soemthing still is broken. Maybe
> something I did wrong?

I think so. I did a fresh install as I wrote and it works perfectly.

**Comment by m0urs** [comment]
Hi Frank,

found the issue, just for your information. The PHP setting
"short_open_tag" needs to be set to "On" as you are using short tags in
your code ;-) By default this was set to "Off" in my PHP installation. Now
the errors are gone.

short_open_tag On

Regards,
Michael

2016-02-23 14:17 GMT+01:00 Frank Tamás notifications@github.com:

> > On 2016. febr. 23., at 14:12, Michael Urspringer <
