### ISSUE TITLE
Spaces in totpIssuer will cause Google Authenticator to fail 

### ISSUE THREAD

**Issue by vittala** [NIIF/simplesamlphp-module-authtfaga#8]
In https://github.com/NIIF/simplesamlphp-module-authtfaga/blob/master/lib/Auth/Source/authtfaga.php#L254, _urlencode_ is called on the otpauth:// URL so it can be passed to googleapis to make a QR code. Any spaces in the totpIssuer value will not be URL encoded, so will result in a otpauth:// URL containing spaces. Google authenticator will not accept this.

Rather than _urlencode_, _rawurlencode_ should be used which will convert spaces to %20.

**Comment by sitya** [comment]
Thanks. Commited.
